fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    ntp:
      repo: "https://github.com/puppetlabs/puppetlabs-ntp.git"
      ref: "4.2.0"
    profile_base: "https://github.com/relybv/dirict-profile_base.git"
    rspec_monitor: "https://github.com/pgomersbach/test-rspec_monitor.git"
    rsyslog: "https://github.com/saz/puppet-rsyslog.git"
    profile_rsyslog: "https://github.com/relybv/dirict-profile_rsyslog.git"
    motd: "https://github.com/puppetlabs/puppetlabs-motd.git"
    lvm: "https://github.com/puppetlabs/puppetlabs-lvm.git"
    gai: "https://github.com/smoeding/puppet-gai.git"
    profile_users: "https://github.com/relybv/dirict-profile_users.git"
    accounts: "https://github.com/puppetlabs/puppetlabs-accounts.git"
    sudo: "https://github.com/saz/puppet-sudo.git"

  symlinks:
    role_monitor: "#{source_dir}"
